#! /usr/bin/env python3
"""A JSON proto server."""

from subprocess import PIPE, CalledProcessError, run

from jsonproto import JSON, spawn


def handler(json: JSON) -> JSON:
    """A JSON message handler."""

    try:
        result = run(json, stdout=PIPE, stderr=PIPE, check=True, text=True)
    except CalledProcessError as error:
        return {
            'state': False,
            'stdout': error.stdout,
            'stderr': error.stderr,
            'returncode': error.returncode
        }

    return {
        'state': True,
        'stdout': result.stdout,
        'stderr': result.stderr,
        'returncode': result.returncode
    }


def main():
    """Runs the server."""

    spawn('127.0.0.1', 9000, handler)


if __name__ == '__main__':
    main()
